### ISSUE TITLE
V1.05 Mission 25 Description bugs(after updating from V1.0)

### ISSUE THREAD

**Issue by NeoEx0** [Taludas/Anno2205-NewFrontiers#16]
IntelliWear has been fulfilled even though i dont have any and its says "0/0"
at the Bottom: No LOCO DUMMYTEXT

![Anno 22052024-6-6-19-22-43](https://github.com/Taludas/Anno2205-NewFrontiers/assets/58145704/e7ee65e0-487c-4733-abeb-bb4e9e6828e7)

**Comment by Taludas** [comment]
Did you have the quest active before the update? Or unlocked it afterwards?

**Comment by Taludas** [comment]
Edit: I have changed the layout of the quest since the last updates: the IntelliWear quest should work correctly if you haven't started the quest before updating.

The quest is working fine for me on a new save in German/English language:
![image](https://github.com/Taludas/Anno2205-NewFrontiers/assets/64583643/a585c538-9b18-45bd-86ef-a0158edf92cb)
