### ISSUE TITLE
Neue Baugebäude freigeschaltet

### ISSUE THREAD

**Issue by wiedehoeft** [Taludas/Anno2205-NewFrontiers#19]
Mir ist noch aufgefallen, dass die Meldung bzgl. der Freischaltung neuer Gebäude recht häufig und fälschlicherweise angezeigt wird.

Regelmäßig wenn ich den Sektor wechsel sagt er mir wieder, dass das Firmen-HQ freigeschaltet wird.
Nachdem ich auf dem Mars angekommen bin wird regelmäßig angezeigt, dass neue Mond-Gebäude freigeschaltet wurden. Vermutlich sind hier "Mars"-Gebäude gemeint, allerdings sind dann entweder keine neuen freigeschaltet worden, oder es sind bereits alle freigeschaltet und die Meldung erscheint trotzdem regelmäßig.

**Comment by Taludas** [comment]
Bitte erst die Known Issues Liste lesen, before ein neues Issue erstellt wird:
"- The unlock notification for new buildings on the Moon has been changed, so that all newly unlocked Moon buildings will show up as "New Moon Buildings" in the notification.

- To manage the build menu and to restrict Mars buildings to the Mars sector, I had to use a workaround by locking the Moon buildings when entering the Mars session. When you leave the Mars session (for example to adjust trade routes), you will get a notification, that again "New Moon Buildings" have been unlocked. I already shortened the notification by using the "New Moon Buildings" pool, but if I disable them completely, you will get no notification on first unlock."

Und zum Firmenhauptquartier steht in den Changelogs:
- "limit Cooporation HQ to one per sector (will be locked again in buildmenu after you have built one in the sector)"

Von daher alles richtig, so wie es ist. Die Features die ich haben möchte gehen nicht anders umzusetzen.
