### ISSUE TITLE
Drake Bug

### ISSUE THREAD

**Issue by Norion1800** [Taludas/Anno2205-NewFrontiers#8]
I got a Drake Invasion in the Arctic where he says he is here for 00:00 Minutes and i need to destroy -1/-1.  Cannot get him away and he is kinda destroying my chains.   
Do you know the GUID for that event so i can remove it like the false Mars effects on the moon?
![screenshot_2024-05-26-23-06-59](https://github.com/Taludas/Anno2205-NewFrontiers/assets/148073801/32878f55-ea28-4997-9a3d-658761ffb014)

**Comment by Taludas** [comment]
Hi, thanks for the report. Had the same just a few moments ago in the beta testers group too.
I don't have a clue why this is happening, apart from the introduction of the seasons on Mars ofc. 

Well, at least, you can fix it yourself easily with the console, select the quest first so that it is the active one (like in the picture), then press Shift+F1 to open the console, type
`quests.reachSelectedQuest()`
and the quest should be completed and gone after a few seconds.
Shift+F1 again to close the console.

With the next update I'm going to add this to the known issues list.
